import { useState } from "react";
import { Link } from "react-router-dom";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import Cal from "@calcom/embed-react";
import { ArrowRight, Brain, CheckCircle2, ChevronDown, FileText, Megaphone, MessageSquare, Mic, MousePointer2, PhoneCall, Send, Sparkles, Video, Zap } from "lucide-react";
import ScrollReveal from "@/components/ScrollReveal";

const CAL_LINK = "figfalcon/figfalcon-strategy-call";
const services = [
  { icon: Mic, title: "AI voice receptionist", copy: "Every serious enquiry gets an immediate response, qualification, and a clear route to your calendar.", link: "/ai-voice-agent" },
  { icon: Video, title: "Ads and AI video creation", copy: "Creative and campaigns designed to make the right prospects stop, understand your offer, and act.", link: "/ai-content-system" },
  { icon: Brain, title: "Company OS", copy: "The operating system that keeps client information, delivery, and follow through from living in your team’s heads.", link: "/second-brain-os" },
];
const faqs = [
  ["What happens in the audit?", "You get a clear view of the points where demand, response, qualification, and booking are costing you conversations, plus the practical priorities to fix first."],
  ["Who is this for?", "It is for owners and decision makers at professional service businesses that can serve more qualified clients and are ready to build a dependable acquisition system."],
  ["Do you replace my team?", "No. We remove repetitive response and follow up work so your people can spend more time on the conversations and client work that need their judgment."],
  ["What does qualified mean?", "The rules are set with you before launch. Service fit, urgency, location, budget, and capacity can all become part of the booking flow."],
] as const;
const scrollToBooking = () => document.getElementById("booking")?.scrollIntoView({ behavior: "smooth", block: "start" });

const HeroMachine = () => {
  const reduced = useReducedMotion();
  return <motion.div initial={{ opacity: 0, scale: 0.92, rotate: 2 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: 0.8, delay: 0.2 }} className="relative w-full min-h-[430px] rounded-3xl border border-primary/30 bg-card/80 p-5 sm:p-7 shadow-[0_24px_80px_-24px_hsl(var(--primary)/0.45)] overflow-hidden">
    <motion.div animate={reduced ? {} : { scale: [1, 1.04, 1], opacity: [0.55, 1, 0.55] }} transition={{ duration: 3.2, repeat: Infinity }} className="absolute -top-24 -right-24 size-64 rounded-full bg-primary/25 blur-3xl" />
    <div className="relative flex items-center justify-between mb-8"><span className="text-xs font-bold tracking-[0.18em] uppercase text-primary">Your growth command center</span><span className="flex gap-2 items-center text-xs text-accent"><span className="glow-dot" /> Live</span></div>
    <div className="relative grid grid-cols-2 gap-3 mb-3"><MachineCard icon={Megaphone} title="Ads live" note="New demand" delay={0.3} /><MachineCard icon={PhoneCall} title="AI answers" note="Instantly" delay={0.45} /></div>
    <motion.div whileHover={{ y: -5, scale: 1.01 }} className="relative rounded-2xl border border-primary/30 bg-primary/10 p-5 mb-3"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground mb-1">New enquiry</p><p className="font-heading font-bold">Qualified consultation</p></div><motion.div animate={reduced ? {} : { rotate: [0, 12, 0] }} transition={{ duration: 1.5, repeat: Infinity }}><Zap className="w-7 h-7 text-primary" /></motion.div></div><div className="mt-4 h-2 rounded-full bg-secondary overflow-hidden"><motion.div initial={{ width: "0%" }} animate={{ width: "86%" }} transition={{ duration: 1.5, delay: 0.8 }} className="h-full rounded-full bg-gradient-to-r from-primary to-cyan-400" /></div></motion.div>
    <div className="relative grid grid-cols-[1fr_auto] gap-3"><motion.div whileHover={{ x: 4 }} className="rounded-xl border border-border/70 bg-secondary/60 p-4"><p className="text-xs text-muted-foreground">Decision maker notified</p><p className="mt-1 text-sm font-semibold">Everything you need before the call</p></motion.div><motion.div animate={reduced ? {} : { y: [0, -5, 0] }} transition={{ duration: 2.2, repeat: Infinity }} className="rounded-xl bg-accent/15 border border-accent/30 flex items-center px-4"><CheckCircle2 className="w-5 h-5 text-accent" /></motion.div></div>
  </motion.div>;
};
const MachineCard = ({ icon: Icon, title, note, delay }: { icon: typeof Megaphone; title: string; note: string; delay: number }) => <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay }} whileHover={{ y: -5 }} className="rounded-2xl border border-border/60 bg-secondary/60 p-4"><Icon className="w-5 h-5 text-primary mb-5" /><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground mt-1">{note}</p></motion.div>;
const Head = ({ eyebrow, children, copy }: { eyebrow: string; children: React.ReactNode; copy?: string }) => <ScrollReveal className="text-center max-w-3xl mx-auto mb-14"><p className="text-xs uppercase tracking-[0.2em] font-bold text-primary mb-4">{eyebrow}</p><h2 className="section-heading mb-4">{children}</h2>{copy && <p className="text-muted-foreground text-lg leading-relaxed">{copy}</p>}</ScrollReveal>;
const Bento = ({ icon: Icon, title, copy, className = "" }: { icon: typeof Mic; title: string; copy: string; className?: string }) => <ScrollReveal><motion.div whileHover={{ y: -6 }} className={`glass-card p-7 h-full relative overflow-hidden ${className}`}><motion.div whileHover={{ rotate: 12, scale: 1.1 }} className="w-11 h-11 bg-primary/10 text-primary rounded-xl flex items-center justify-center mb-10"><Icon className="w-5 h-5" /></motion.div><h3 className="font-heading font-semibold text-xl mb-3">{title}</h3><p className="text-sm leading-relaxed text-muted-foreground max-w-xl">{copy}</p></motion.div></ScrollReveal>;
const FlowCard = ({ number, title, copy, icon: Icon }: { number: string; title: string; copy: string; icon: typeof Mic }) => <ScrollReveal><motion.div whileHover={{ y: -8 }} className="glass-card p-7 h-full"><div className="flex justify-between items-start"><span className="text-sm text-primary font-bold">{number}</span><motion.div animate={{ rotate: [0, 8, 0] }} transition={{ duration: 3, repeat: Infinity }}><Icon className="w-5 h-5 text-primary" /></motion.div></div><h3 className="font-heading font-semibold text-xl mt-12 mb-3">{title}</h3><p className="text-sm text-muted-foreground leading-relaxed">{copy}</p></motion.div></ScrollReveal>;

const Index = () => {
  const [open, setOpen] = useState<number | null>(null);
  return <>
    <section className="relative overflow-hidden pt-32 pb-24 lg:pt-40 lg:pb-32"><div className="absolute inset-0 gradient-hero" /><div className="absolute inset-0 grid-pattern opacity-20" /><div className="container mx-auto px-6 relative"><div className="grid lg:grid-cols-2 gap-14 xl:gap-20 items-center"><div><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55 }} className="section-badge mb-7 w-fit"><Sparkles className="w-4 h-4" /> The Consult Recovery System</motion.div><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, delay: 0.08 }} className="font-heading font-bold text-5xl sm:text-6xl xl:text-7xl leading-[0.98] tracking-tight mb-7">Turn your attention into <span className="gradient-text">qualified conversations.</span></motion.h1><motion.p initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65, delay: 0.16 }} className="text-lg sm:text-xl text-muted-foreground max-w-xl leading-relaxed mb-9">FigFalcon gives owners one connected growth system. We create the demand, answer every serious enquiry, and keep the operational work moving after the call.</motion.p><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }} className="flex flex-wrap gap-4"><Link to="/contact" className="btn-primary text-base px-7 py-4">Get a Consult Recovery Audit <ArrowRight className="w-5 h-5" /></Link><button onClick={scrollToBooking} className="btn-secondary text-base px-7 py-4">Speak with our team</button></motion.div><div className="flex flex-wrap gap-x-6 gap-y-3 mt-7 text-sm text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-accent" /> Ads and content</span><span className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-accent" /> AI call handling</span><span className="flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-accent" /> Company OS</span></div></div><HeroMachine /></div></div></section>
    <section className="py-24 border-y border-border/30 bg-secondary/10"><div className="container mx-auto px-6 max-w-6xl"><Head eyebrow="Built for the person carrying the number" copy="You do not need another disconnected tool. You need the whole journey to work from the first impression to the booked conversation and beyond.">Three systems. <span className="gradient-text">One growth engine.</span></Head><div className="grid md:grid-cols-3 gap-5">{services.map(({ icon: Icon, title, copy, link }, i) => <ScrollReveal key={title} delay={i * 0.1}><Link to={link} className="block group h-full"><motion.div whileHover={{ y: -8 }} className="glass-card h-full p-7 relative overflow-hidden"><motion.div animate={{ rotate: [0, 7, 0] }} transition={{ duration: 4 + i, repeat: Infinity }} className="absolute -right-8 -top-8 size-24 rounded-full bg-primary/10 blur-xl" /><div className="relative"><div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary mb-12"><Icon className="w-6 h-6" /></div><h3 className="font-heading text-xl font-semibold mb-3">{title}</h3><p className="text-sm text-muted-foreground leading-relaxed">{copy}</p><span className="mt-7 inline-flex gap-2 items-center text-sm font-semibold text-primary">Explore this system <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" /></span></div></motion.div></Link></ScrollReveal>)}</div></div></section>
    <section className="py-24"><div className="container mx-auto px-6 max-w-6xl"><Head eyebrow="The change" copy="Most owners already have enough activity to grow. The real loss happens between interest and the next meaningful action.">Where growth <span className="gradient-text">quietly disappears.</span></Head><div className="grid lg:grid-cols-3 gap-5"><Bento icon={Megaphone} title="Demand without direction" copy="Your message reaches people, but it does not give the right ones a compelling next move." className="lg:col-span-2" /><Bento icon={Mic} title="Calls that wait" copy="When response depends on who is free, valuable interest loses momentum." /><Bento icon={FileText} title="Information trapped everywhere" copy="Client context, decisions, and follow through should not disappear into private inboxes." /><Bento icon={MessageSquare} title="More leads is not the goal" copy="The goal is a qualified conversation on your calendar with enough context to make it valuable." className="lg:col-span-2" /></div></div></section>
    <section className="py-24 bg-secondary/10"><div className="container mx-auto px-6 max-w-6xl"><Head eyebrow="What happens when it is connected">A better experience for the buyer. <span className="gradient-text">More control for you.</span></Head><div className="grid md:grid-cols-3 gap-5"><FlowCard number="01" title="Get found" copy="Ads and content turn attention into relevant enquiries." icon={MousePointer2} /><FlowCard number="02" title="Respond now" copy="AI handles the first response while interest is at its highest." icon={Send} /><FlowCard number="03" title="Run the follow through" copy="Your Company OS gives the right person the right context at the right time." icon={Brain} /></div><ScrollReveal className="text-center mt-10"><Link to="/contact" className="btn-primary px-7 py-4">Get a Consult Recovery Audit <ArrowRight className="w-5 h-5" /></Link></ScrollReveal></div></section>
    <section className="py-24"><div className="container mx-auto px-6 max-w-5xl"><Head eyebrow="A practical first conversation" copy="The Consult Recovery Audit is for owners who want to understand the gaps before they invest in more activity.">See what your growth system is <span className="gradient-text">leaving on the table.</span></Head><div className="grid lg:grid-cols-2 gap-6"><ScrollReveal><motion.div whileHover={{ y: -5 }} className="glass-card p-8 h-full"><FileText className="w-7 h-7 text-primary mb-6" /><h3 className="font-heading font-semibold text-2xl mb-5">What you leave with</h3>{["A map of demand and response gaps", "Clear priorities for qualification and booking", "A candid view of whether a system build makes sense"].map(item => <p key={item} className="flex gap-3 text-sm text-muted-foreground mb-4"><CheckCircle2 className="w-4 h-4 text-accent shrink-0 mt-0.5" />{item}</p>)}</motion.div></ScrollReveal><ScrollReveal delay={0.1}><motion.div whileHover={{ y: -5 }} className="glass-card p-8 h-full border-primary/30"><FileText className="w-7 h-7 text-primary mb-6" /><h3 className="font-heading font-semibold text-2xl mb-5">Who gets the most value</h3><p className="text-muted-foreground leading-relaxed mb-6">Decision makers at professional service businesses who have the capacity to take on more of the right clients and want a system they can trust.</p><Link to="/contact" className="btn-primary">Get a Consult Recovery Audit <ArrowRight className="w-4 h-4" /></Link></motion.div></ScrollReveal></div></div></section>
    <section className="py-24 border-t border-border/30"><div className="container mx-auto px-6 max-w-3xl"><Head eyebrow="Questions decision makers ask">Before you take the next step</Head><div className="space-y-3">{faqs.map(([question, answer], i) => <ScrollReveal key={question} delay={i * 0.05}><div className="glass-card overflow-hidden"><button onClick={() => setOpen(open === i ? null : i)} className="w-full p-5 flex items-center justify-between text-left gap-5"><span className="font-heading font-semibold">{question}</span><ChevronDown className={`w-5 h-5 text-primary transition-transform ${open === i ? "rotate-180" : ""}`} /></button><AnimatePresence>{open === i && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="px-5 pb-5 text-sm text-muted-foreground leading-relaxed">{answer}</p></motion.div>}</AnimatePresence></div></ScrollReveal>)}</div></div></section>
    <section className="py-24 bg-secondary/10" id="booking"><div className="container mx-auto px-6 max-w-4xl"><Head eyebrow="Strategy conversation" copy="Bring the bottleneck you are trying to solve. We will show you how demand, response, and operations can work as one system.">Make your next growth move <span className="gradient-text">with clarity.</span></Head><ScrollReveal><div className="rounded-2xl overflow-hidden border border-border/40 shadow-xl"><Cal calLink={CAL_LINK} style={{ width: "100%", height: "100%", overflow: "scroll" }} config={{ layout: "month_view", theme: "dark" }} /></div></ScrollReveal></div></section>
  </>;
};
export default Index;
